const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src: './images/kurly_003.jpg',
        name: '[서울우유] 멸균우유 1000ml',
        summary: '깔끔하고 신선한 맛의 멸균우유',
        price: 1980,
        sale: 10,
        review: 320,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[농심] 신라면 블랙 두 개입',
        summary: '깊은 국물맛의 프리미엄 라면',
        price: 2800,
        sale: 15,
        review: 87,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[하림] 닭가슴살 1kg',
        summary: '담백하고 건강한 단백질',
        price: 9800,
        sale: 25,
        review: 201,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[청정원] 햇살담은 간장 500ml',
        summary: '요리에 감칠맛을 더하는 전통 간장',
        price: 2500,
        sale: 5,
        review: 43,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[빙그레] 바나나맛 우유 240ml',
        summary: '달콤한 국민 간식 바나나맛',
        price: 1300,
        sale: 0,
        review: 512,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[풀무원] 얇은피 꽉찬속 만두 420g',
        summary: '바삭하고 속이 꽉 찬 만두',
        price: 4680,
        sale: 12,
        review: 298,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[CJ] 햇반 210g x 3개입',
        summary: '전자레인지에 간편하게 조리',
        price: 3900,
        sale: 8,
        review: 134,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[오뚜기] 진라면 매운맛 5개입',
        summary: '매콤한 국물 맛이 일품',
        price: 3980,
        sale: 18,
        review: 176,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[롯데] 초코파이 12개입',
        summary: '부드러운 마시멜로와 초코의 조화',
        price: 5200,
        sale: 10,
        review: 289,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[동원] 리챔 200g x 3개입',
        summary: '고소하고 담백한 햄의 대표주자',
        price: 8700,
        sale: 14,
        review: 95,
    }
]